### ISSUE TITLE
Broken regex when using trailing slash in the dir name on MANIFEST.in

### ISSUE THREAD

**Issue by thenets** [ansible/ansible-sign#16]
The sign command breaks when using a trailing slash in the dir name on MANIFEST.in.

### 💚 Condition that works

`MANIFEST.in`:
```ini
recursive-include playbooks *.yml
```

`Command:`

```bash
(global) [luiz@workstation ansible-test-content]$ ansible-sign project gpg-sign .
```

### ❤️ Condition that fails

`MANIFEST.in`:
```ini
recursive-include playbooks/ *.yml
```

`Command:`

```bash
(global) [luiz@workstation ansible-test-content]$ ansible-sign project gpg-sign .
> [2022-08-30 09:15:56] WARNING:distlib.manifest:no files found matching '*.yml' under directory 'playbooks/'
```

**Comment by relrod** [comment]
We rely on `distlib.manifest` for the `MANIFEST.in` behavior and this behavior is coming directly from that library. I don't think there is anything for us to do here.
