### ISSUE TITLE
test automation for ansible-sign

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/ansible-sign#3]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Ensure that automation for ansible-sign is tested. This will include unit and integration tests. Should be able to parse the arguments as if running through the CLI. 

We(Luiz) also going to write up some for the integration test suite. 

In the context specifically of Ansible Sign. 

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

**Comment by relrod** [comment]
I'm comfortable closing this and moving to done, since it is specifically dealing with the CLI part which is well-tested now, compared to when this ticket was made.
